// Class automatically generated by Dev-C++ New Class wizard

#ifndef TRANSMATRIX_H
#define TRANSMATRIX_H
#include "MathLibrary.h"
/*
 * No description
 */
class TransMatrix
{
	public:
		// class constructor
		TransMatrix();
		// class destructor
		~TransMatrix();
		mat4 IdentidyMx();
		mat4 TranslationMxf(float x,float y,float z);
		mat4 TranslationMxv(vec3 Vector);
		mat4 ScaleMxf(float x,float y,float z);
		mat4 ScaleMxv(vec3 Vector);
		mat4 RotateXMxf(float phi);
		mat4 RotateYMxf(float theta);
		mat4 RotateZMxf(float psi);
		mat4 RotateXYZMxf(float phi,float theta,float psi);
		mat4 ViewMx(vec3 Origin,vec3 Target,vec3 Up);
		mat4 PerspectiveMx(float fov, float aspect,float znear, float zfar);
};

#endif // TRANSMATRIX_H